### ISSUE TITLE
HinSAGENodeGenerator's `head_node_type` parameter is unintuitive when working with a graph with just a default node type.

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#1023]
### Description

A heterogeneous graph could contain multiple edge types, but only a single node type, in which case the user may simply be using the default node type. `graph.info` shows the node type as "default", but the user never explicitly creates a node type called "default". Then, when they try to create a `HinSAGENodeGenerator` with the graph, the `head_node_type` parameter can be a bit puzzling since they wouldn't remember ever creating any node types at all.

In the generator, we could consider some options like:
* infer the head node type if there is only one node type available in the graph
* make it more transparent to the user when nodes/edges are assigned the "default" type while creating the graph.
* update the docs to guide the user better

**Comment by kjun9** [comment]
(cc @annitrolla )

**Comment by huonw** [comment]
I think the only way this issue can come up is in a homogeneous graph `one_node_type_graph`, since that's the only time that the user has no reason to be thinking about node types. Thus, #1375 hopefully addresses this by making `HinSAGENodeGenerator(one_node_type_graph, batch_size=2, num_samples=[3, 4])` work.
