### ISSUE TITLE
dataload() giving error: G, node_subjects = dataset.load() Core has no attribute load

### ISSUE THREAD

**Issue by engrAsmasaattar** [stellargraph/stellargraph#1084]
### Describe the bug

*A clear and concise description of what the bug is.*

### To Reproduce

1. *Go to '...'*
2. *Execute '...'*
3. *See error*

### Observed behavior

*Describe or paste the exact output that demonstrates the bug (for example, the stack trace if it is an exception).*

### Expected behavior

*A clear and concise description of what you expected to happen.*

### Environment

Operating system: *for example: macOS, Ubuntu*

Python version: *for example: 3.7.2*

Package versions: *for example: stellargraph==0.8.3, tensorflow==2.0.0*

*The following Python code can automatically compute the data for this section (for example: run the code in a Jupyter notebook cell, or, on macOS, copy the code and run `pbpaste | python -` in a terminal):*
~~~
import subprocess, platform, sys
pkgs = subprocess.Popen(["pip", "freeze"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0].decode("utf-8")
print("Operating system: `{}`\nPython version:\n```\n{}\n```\nPackage versions:\n<details>\n\n```\n{}\n```\n\n</details>".format(platform.platform(), sys.version, pkgs))
~~~

### Additional context

Add any other context about the problem here. For example:

Data used: *if this occurs with a specific dataset, which dataset and how to acquire it*

Screenshots: *if applicable, add some screenshots to explain the behaviour*

**Comment by huonw** [comment]
Hi, thanks for trying StellarGraph! We'd love to help you, and so it's really good if we have more information. Our bug template has all of that information because it helps us immediately narrow down the problem and get to a solution straight away.

- What are you doing to see this error? Are you running a notebook? If so, which one?
- What version of StellarGraph are you using? (You can find this with `pip freeze` on the command line, or `import stellargraph; print(stellargraph.__version__)` in Python)

My guess is you're using one of the latest development release versions of our notebooks. However, we've been changing our demo notebooks recently, and so the version on the `develop` branch won't work with the most recent release 0.10.0. You can get the 0.10 versions in two ways:

- online, make sure you're looking at the `v0.10.0` tag, e.g. https://github.com/stellargraph/stellargraph/tree/v0.10.0/demos (note the `v0.10.0` after the `tree`)
  ![image](https://user-images.githubusercontent.com/1203825/76804498-878b6580-6830-11ea-9ea9-8965403034fa.png)
- on the command line, run `git checkout v0.10.0` to jump to that tag

Please let us know if that helps, and if it doesn't let us know more information about the problem. Thanks!

**Comment by huonw** [comment]
It's been 2 months without any update, so I'm going to assume that the problem is resolved. If we haven't heard otherwise in a week or so, we'll close. (But, even if we close, feel free to just let us know later, and we can reopen/continue the discussion.)
