### ISSUE TITLE
Make L2-normalisation of the final embeddings in GraphSAGE and HinSAGE optional

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#115]
### Description
Currently, L2 normalisation is applied to the final node embeddings in GraphSAGE and HinSAGE layers, as @kjun9 pointed out. What this does is puts all node vectors onto surface of a radius 1 sphere in the embedding space. This seems like a sensible thing to do, but it also essentially removes 1 degree of freedom from the embeddings (yet this might not be a big problem for high embedding space dimensionalities of >=100). Perhaps we can make the L2 normalisation optional?

### Done Checklist (Development)
- [x] Produced code for required functionality
- [x] Branch and Pull Request build on CI
- [x] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Version number reflects new status
- [x] Peer Code Review Performed
- [x] Code well commented
- [ ] Documentation in repo

**Comment by kkonevets** [comment]
> I tend to agree - I don't have a feeling for how this normalization affects the solutions or the convergence of the model.  It does make sense in many ways and perhaps adds some regularization to the solutions, but it would be interesting to test different normalizations. 
> 
> 
> 
> It will be straightforward to make this optional - @kjun9 wrote GraphSAGE and HinSAGE so that we just have to set self._normalization to the identity function.

I can tell that L2 normalization is essential for good model score, e.g. precision. I found that a lack of it decreases the score on my task. I do node classification. I guess the reason is that L2 captures features relative relations. Each step of aggregation takes as an input L2 normalized features. For example, if we have a social network then the amount of male/female friends a user has does not matter, only the percentage of male/female friends he /she has in case of we want to determine a user’s gender. So magnitude does not matter in this case
