### ISSUE TITLE
Node prediction/classification by using a trained model for a new graph with unlabelled nodes

### ISSUE THREAD

**Issue by qillbel** [stellargraph/stellargraph#1235]
Dear all

I'm following some of the demos in (i.d. GCN, GAT, and GraphSAGE), where training and testing the model is performed. In those demos, all the training, validating, and testing are done with the labelled nodes in order to generate a predictive model. I have done those steps with my datasets and get a trained model. 

My question is, if I have a set of completely new graphs with unlabelled nodes on them, how do I use my trained model to predict/classify those nodes? Would it be possible to show with some line of codes similar with the Jupiter notebook in the demo?

Thanks

**Comment by kjun9** [comment]
Hi @qillbel 

Thanks for trying out our library!

The exact details of what kind of pipeline is suitable for you will depend on your data, but sounds like you have a homogeneous graph that you're training your model on, and you want to predict on nodes in another graph?

Since GraphSAGE is an inductive method, if you've been able to train a model with GraphSAGE already, you should be able to use your trained model to classify nodes in a new graph - take a look at [this demo notebook](https://github.com/stellargraph/stellargraph/blob/master/demos/node-classification/graphsage/graphsage-pubmed-inductive-node-classification-example.ipynb) which trains a model with a reduced graph then predicts on nodes in a larger graph. You can skip to the section called `Making predictions with the model` if you're familiar with the training workflow already:

> We want to use the trained model to predict the nodes we put aside earlier. For this, we must use the original StellarGraph object and a new node generator.
> 
> The new generator feeds data from this full graph into the model trained on the sampled partial graph

The demo notebook doesn't predict on an *entirely* new graph, but does show that we're able to predict on nodes that weren't seen during training. So applying the same prediction workflow with a completely new graph should work in theory, with the assumption that nodes in the new graph has features in the same feature-space as the original graph you trained on. Otherwise there will either be a dimension mismatch or the results will be meaningless when you run the prediction.

GAT is also an inductive method, but unfortunately we don't currently support inductive learning with GAT (https://github.com/stellargraph/stellargraph/issues/1076). 

Let us know how it goes and feel free to ask me to clarify or provide us with more details so we can help you further!

**Comment by huonw** [comment]
It's been a month without any update, so I'm going to assume that the problem is resolved. If we haven't heard otherwise in a week or so, we'll close. (But, even if we close, feel free to just let us know later, and we can reopen/continue the discussion.)
