### ISSUE TITLE
AttributeError: 'StellarGraph' object has no attribute 'nvtxs'

### ISSUE THREAD

**Issue by davidxujiayang** [stellargraph/stellargraph#1239]
I'm trying to use metis to partition a graph following a similar approach as in the cluster GCN example in node classification. The relavant lines are

```
G, A, coords, data = build_graph_from_vtm(
    'data/airfoil/test_7.vtm', 'data/airfoil/polyMesh', ['p', 'U'], plot=False)
print(G.info())
number_of_clusters = 50
edgecuts, parts = metis.part_graph(G, number_of_clusters)
```
And the error outputs are (based on which I think I've generated the graph correctly):

> StellarGraph: Undirected multigraph
>  Nodes: 11092, Edges: 21254
> 
>  Node types:
>   default: [11092]
>     Features: float32 vector, length 2
>     Edge types: default-default->default
> 
>  Edge types:
>     default-default->default: [21254]
> Traceback (most recent call last):
>   File "stella_cfd.py", line 40, in <module>
>     edgecuts, parts = metis.part_graph(G, number_of_clusters)
>   File "/home/davidxu/anaconda3/envs/cfd/lib/python3.7/site-packages/metis.py", line 791, in part_graph
>     partition = (idx_t*graph.nvtxs.value)()
>   File "/home/davidxu/anaconda3/envs/cfd/lib/python3.7/site-packages/stellargraph/core/graph.py", line 436, in __getattr__
>     return super().__getattribute__(item)
> AttributeError: 'StellarGraph' object has no attribute 'nvtxs'

**Comment by PantelisElinas** [comment]
Hi davidxujiayang,

thanks for using StellarGraph. 

I think we have an error in the notebook because when using Metis, `G` should be a `Networkx` object not `StellarGraph`. It is possible to convert a `StellarGraph` object to `Networkx` using the method `StellarGraph.to_networkx()` (see the docs at https://stellargraph.readthedocs.io/en/stable/api.html#stellargraph.StellarGraph.to_networkx). So, first convert your object to `Networkx` and then call `metis.part_graph(...)` to get the `clusters`. Remember that after you have the clusters, you need your `StellarGraph` object for machine learning. 

We will update the demo over the next few days to fix this error. In the meantime, let us know if you can't get the above to work.

Regards,

P.

**Comment by davidxujiayang** [comment]
Hi Pantelis,

Thanks for your reply and suggestion. It works!

Best,
-David

Xu, Jiayang (David)
PhD Candidate
Computational Aerosciences Laboratory
Department of Aerospace Engineering
University of Michigan

**Comment by PantelisElinas** [comment]
Hi @davidxujiayang 

glad it worked for you. We have also updated our demo notebook in the **develop** branch to correct for the bug you identified. It is a different solution to the one I proposed above and should work with the latest `NetworkX` version.

Thank you and all the best!

P.

**Comment by davidxujiayang** [comment]
Hi,

Thanks again for letting me know, I'll check it out. BTW your library is
awesome and extremely helpful!

All the best~
David

Xu, Jiayang (David)
PhD Candidate
Computational Aerosciences Laboratory
Department of Aerospace Engineering
University of Michigan
