### ISSUE TITLE
Graph.info shows directed edge types in an undirected graph

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#1312]
### Describe the bug

Current behaviour is to show the edge type triples `A-R->B` and `B-R->A` separately in the info string even when the graph is undirected. We should probably be collapsing them into one?

**Comment by huonw** [comment]
Reproducing example (it would've be good to include at least something basic, so that we can understand specifically what this issue is about in future).

```python
import stellargraph as sg
import pandas as pd

nodes = {"A": pd.DataFrame(index=[0, 1]), "B": pd.DataFrame(index=[2])}
edges = pd.DataFrame({"source": [0, 2], "target": [2, 1]})
print(sg.StellarGraph(nodes, edges).info())
```

This graph has edges `0 (A) -> 2 (B)` and `2 (B) -> 1 (A)`.

### Observed output

```
StellarGraph: Undirected multigraph
 Nodes: 3, Edges: 2

 Node types:
  A: [2]
    Features: none
    Edge types: A-default->B
  B: [1]
    Features: none
    Edge types: B-default->A

 Edge types:
    B-default->A: [1]
    A-default->B: [1]
```


### Expected output

Something like:

```
StellarGraph: Undirected multigraph
 Nodes: 3, Edges: 2

 Node types:
  A: [2]
    Features: none
    Edge types: A-default->B
  B: [1]
    Features: none
    Edge types: B-default->A

 Edge types:
    A-default->B: [2]
```

### Versions

Stellargraph bcde23a37531256321853f44a233e8b48d8fc455
