### ISSUE TITLE
Demos should do some basic data exploration to hint at what a user needs to load

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1331]
### Describe the bug

Along the lines of #1330, it's helpful if demos have some indication of what the hidden loading code is doing. One form of this is showing/telling what the result of the loading is, e.g. that's it's a StellarGraph or list of StellarGraphs (for graph classification) and what's in the graph(s) (via `info()`), and similarly for any other pieces of information that are loaded.

(StellarGraph 1.0.0rc1 dogfooding)

**Comment by timpitman** [comment]
We could potentially automate this, eg:

**Comment by yvonnegh** [comment]
User doesn't have a sense of what data is used in the demo
eg.
- here is the info of the graph
- here are the number of graphs
Applies to lots of demos, and has to be done manually, so is potentially quite a lot of work.

Could do Graph Classification ones (different to others) - list rather than a graph.
Users coming in may not necessarily know about graph classification.

Not as critical as #1330

**Comment by huonw** [comment]
Calling this done enough for now, with #1628.
