### ISSUE TITLE
Use enums for flag variables

### ISSUE THREAD

**Issue by arc0** [stellargraph/stellargraph#144]
https://github.com/stellargraph/stellar-ml/blob/acfbb255bcb9f8a11c92a860ccf714caa16d7ece/stellar/data/edge_splitter.py#L213

Hi guys, usually string variables shouldn't be used for default arguments in Python as they are mutable.

Moreover it is best practice to use enums for flag arguments
```
from enum import Enum
class NegativeSamples(Enum):
    GLOBAL = 1
    LOCAL = 2

def train_test_split(self, something=NegativeSamples.GLOBAL)
```
Then the enums would float about in a 'utils.py' or 'const.py' file that people import. If the flags are common they can be promoted through __init__.py.

**Comment by huonw** [comment]
Unfortunately, I'm not sure this is a good idea.

- most libraries use strings (and potentially other options too) e.g.:
  - `df.join(..., how="right")` in Pandas https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.join.html ,
  - `numpy.array(..., dtype="int32")`,
  - `Dense(kernel_initializer="uniform")`
- strings aren't mutable in Python (unlike `list`s and `dict`s) so the dangers are more controlled
- using enums is a bit clunky and annoying in Python, since it requires extra imports

We could potentially support both enums (good for "high assurance" cases) and strings (good for ease-of-use), but I'm not sure that's valuable. As such, I'm going to move this to Review/QA for discussion.

**Comment by kjun9** [comment]
Yeah I also don't think we need enums. I'm not sure if it's python libraries in general or just the libraries that are geared towards data-science/notebook workflows, but using strings instead of enums seems to be the preferred approach.
