### ISSUE TITLE
Continuous integration for public facing repos

### ISSUE THREAD

**Issue by arc0** [stellargraph/stellargraph#220]
### Description
What is the strategy for running code from the internet on our internal buildkite servers? We need a plan for how external code is run. Some options include isolated buildkite servers, travisCI

### Done Checklist (Development)
- [ ] Session on public repos
- [ ] CI strategy agreed between ml team + devops

**Comment by TheDen** [comment]
Set up a test repo https://github.com/stellargraph/pipeline-testing/ and buildkite pipeline https://buildkite.com/stellar/pipeline-testing and it works as expected

![image.png](https://images.zenhubusercontent.com/5b189e3ab709d021406865ae/e7353e47-f247-4348-9682-edbfb507b432)

How it works
*At the UI level, the initial command is run that checks if the env var `BUILDKITE_PULL_REQUEST_REPO` and `BUILDKITE_REPO` don't match. 
* Since a forked PR's repo and hence env var `BUILDKITE_PULL_REQUEST_REPO` will be different, i.e., prefixed with their username, the env vars won't match. 
* If the env vars don't match, a dynamic pipeline is created that adds a block step that needs approval from someone within stellargraph. Once approved, the build will run as normal
* The env var `BUILDKITE_NO_LOCAL_HOOKS=true` disables any _local_ hooks, i.e., code that users can inject to change how the buildkite agent behaves.
* Otherwise if hooks are allowed, users can change the env var to match, or worse run arbitrary BK agent code.
* If a user tries to use a hook in their PR, the build won't run and fail (which will raise a red flag)

**Comment by TheDen** [comment]
An example of a blocked fork PR that would need approval https://buildkite.com/stellar/pipeline-testing/builds/30

**Comment by TheDen** [comment]
Now implemented for https://github.com/stellargraph/stellargraph 👍
