### ISSUE TITLE
Improve RAM usage in Stellargraph 

### ISSUE THREAD

**Issue by almugabo** [stellargraph/stellargraph#325]
For graph operations, stellargraph relies on **networkx** which has a very nice API and strong community support.

The heavy memory requirements of networkx however limits the potential of stellargraph to be used as a production tool in realistic contexts (with huge graphs).

- One way to improve this is to add **another graph library** (e.g. igraph) with a better memory management as an optional “back-end” graph processing engine.

I am mentioning igraph as I understand from the documentation below that igraph "(typically) needs 32 bytes per edge and 16 bytes per vertex. A graph with one million vertices and ten million edges needs about 320 Mbytes."
[documentation slides](http://cneurocvs.rmki.kfki.hu/igraph/igraph-final.pdf)

- Another way (maybe longer term) to use directly the data **without a graph library** (e.g. data saved in HDF5 ) to produce the random walks.

Any interest in the community here to explore this further ?

Aha! Link: https://csiro.aha.io/features/SGML-39

**Comment by adocherty** [comment]
Hi @almugabo thanks for the comments and suggestion.  We are aware of the heavy memory usage of NetworkX and are considering using a lighter graph format for StellarGraph. 

In particular, we are looking at separating the `StellarGraph` class from the NetworkX `Graph` class in the future and providing a lighter-weight graph class which only stores what is needed for the graph structure. Formats we are considering are sparse matrix formats, or a custom graph class. We plan to continue to support NetworkX as an easy way to import graphs to `StellarGraph` but plan to extend support to other import methods in order to load large graphs.

If you have any more thoughts on this issue, please post them.

**Comment by almugabo** [comment]
For a long term solution, one idea worth exploring is [compressed sparse graph ](https://docs.scipy.org/doc/scipy/reference/sparse.csgraph.html) from scipy. 

I have not explored it myself yet but if it can easly handle [weights](https://stackoverflow.com/questions/17910041/) then it could be a candidate for a stellargraph own graph format.

**Comment by AlexMRuch** [comment]
Any thoughts on using graph-tool graph objects instead of networkx? My 2GB graph-tool object explodes to 20GB in graphml, and overflows my RAM (over 128GB) when I try to convert to networkx. Networkx is also limited by it's pure python implementation. Graph-tool, by contract, has a mostly C/C++ backend and heavily evokes parallel processing with the option of approximate measures. Its hundreds to thousands of times faster than networkx. Because graph-tool heavily uses numpy, this switch would not be too difficult and would go along with almugabo's suggestion of scipy's compressed sparse graphs. Also, getting all neighbors is as simple as graph.get_vertices(), all edges are obtained with graph.get_edges(), etc. Every node and edge can have properties (e.g., labels, weights, etc.) that can be obtained with graph.vp.vertex_property_name.a. It's quite easy to rewrite functions that don't exist in graph-tool (e.g., bridging centrality) in vectorized forms, in other words.

**Comment by PantelisElinas** [comment]
Hi @AlexMRuch 

thank you for your interest in our work and the code example. Memory and speed optimisations are on our to do list for the next major library release. We are currently evaluating different options for graph representations to potentially replace our dependence on networkx. Your use case and script will be very useful in this process.

Regards,

P.

**Comment by AlexMRuch** [comment]
You're very welcome, @PantelisElinas! If there's any way I can help, let me know!

**Comment by huonw** [comment]
Hi everyone, in 0.9.0, we've got an experimental implementation of `StellarGraph` backed by numpy and pandas (we didn't go with igraph because it seems to be a little awkward to install on some platforms, and it doesn't seem to be optimised for the sort of machine-learning/deep-learning queries that stellargraph uses).

This cuts memory use significantly, e.g. on one dataset (a reddit dataset that includes 1.2GB of node features), memory usage goes from 12.4 GB to 1.8GB. The pull request https://github.com/stellargraph/stellargraph/pull/668 contains some more details, as does the [0.9.0 release notes](https://github.com/stellargraph/stellargraph/releases/tag/v0.9.0) (see "Experimental features"). Working on moving this out of "experimental" continues, with #662 as the umbrella Epic.

This can be tested by using the `StellarGraph(nodes=..., edges=...)` (and `StellarDiGraph(nodes=..., edges=...)` constructor, passing in Pandas DataFrames for a homogeneous graphs, or a `dict` of DataFrames for a heterogeneous graph. The documentation for `StellarGraph` describes these in some more detail: https://stellargraph.readthedocs.io/en/v0.9.0/api.html#stellargraph.core.StellarGraph

Do note that this is **experimental** in the 0.9.0 release: it hasn't been fully tested, has some missing components, and is likely to change significantly before the next release. I think the following models can be successfully trained and predicted:

- GCN
- GAT
- GraphSAGE
- PPNP, APPNP

However, these were only tested on a single small dataset (Cora) and so may not work for larger/more complicated datasets. Other models definitely don't work (HinSAGE), and the rest haven't been tested.

**Comment by AlexMRuch** [comment]
What wonderful news! I'm also happy to hear that you all have chosen to go with numpy/pandas, as those libraries also play nicely with other libraries for deep learning on graphs (e.g., `dgl` can load sparse numpy matrices). Thank you so much for these additions! Looking forward to using them soon!
