### ISSUE TITLE
Enable fast node type lookups in graph class

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#347]
### Description

For many methods we need a fast way to look up a node's type. In particular for homogeneous graphs we can simple return the global node type, for heterogeneous graphs we need a fast lookup table.

When we implement a standardized graph class – see issue #325 –  we should include this functionality.

### Done Checklist (Development)
- [ ] Assumptions of the user story met
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Version number reflects new status
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] Documentation in readthedocs
- [ ] CHANGELOG.md updated

**Comment by huonw** [comment]
Without a point of reference, I think we can stay that this is done, as we now have a `node_type` method that finds the type for a given node:

https://github.com/stellargraph/stellargraph/blob/ecd38f9cc20491358d1828945b84b8d0e0c680ec/stellargraph/core/graph.py#L612-L627

With #870, this will likely be faster, but that issue is tracking this work, so we can call this Done.
