### ISSUE TITLE
RuntimeError in Hinsage model

### ISSUE THREAD

**Issue by treper** [stellargraph/stellargraph#367]
RuntimeError: All (src,dst) node types for inferred links must be of the same type!

What does this mean? I thought Hinsage model is applicable to heterogeneous netwok.

The following is the detail errors:

Traceback (most recent call last):
  File "graph.py", line 722, in <module>
    dropout=args.dropout
  File "graph.py", line 504, in train
    train_gen = generator.flow(edgelist_train, labels_train)
  File "/data/home/anaconda3/lib/python3.6/site-packages/stellargraph/mapper/link_mappers.py", line 435, in flow
    return LinkSequence(self, link_ids, targets)
  File "/data/home/anaconda3/lib/python3.6/site-packages/stellargraph/mapper/link_mappers.py", line 90, in __init__
    self.head_node_types = self._infer_head_node_types(generator.schema)
  File "/data/home/anaconda3/lib/python3.6/site-packages/stellargraph/mapper/link_mappers.py", line 109, in _infer_head_node_types
    "All (src,dst) node types for inferred links must be of the same type!"
RuntimeError: All (src,dst) node types for inferred links must be of the same type!

**Comment by adocherty** [comment]
Hi,

Thanks for trying the library!

While the HinSAGE model is applicable to heterogeneous networks, the link prediction builds a model for a single link type. For example if you have nodes of types 'A' and 'B' you can build a link model for only a single pair of node types, for example ('A', 'B').  If you feed links into the model that do not have these node types (in correct order) you will see this error.

This is because we are assuming that each HinSAGE link prediction models a single link type.  For example, a predictive model of links with node types ('A', 'B') will be different from a model of links with node types ('A',  'A') or ('B', 'B').  To deal with different link types we can, of course, create multiple HinSAGE models.

I hope this helped!
