### ISSUE TITLE
Different generator argument for GCN/GAT model  vs GraphSAGE model

### ISSUE THREAD

**Issue by adocherty** [stellargraph/stellargraph#374]
**Description**

There are currently a few differences between the GCN/GAT model API and the GraphSAGE model API. The first one is the generator argument is different for these models.

Specifically, the GAT/GCN classes take the `generator=` argument expecting a `FullBatchNodeGenerator` object, not a `FullBatchNodeSequence` object. The GraphSAGE/HinSAGE class expect the `NodeSequence` object. This means that we are passing different objects to each class:

e.g. for GAT, from the demo notebook:
```
generator = FullBatchNodeGenerator(G)
train_gen = generator.flow(train_data.index, train_targets)
gat = GAT(
    layer_sizes=[8, train_targets.shape[1]],
    attn_heads=8,
    generator=generator,
...
)
```

e.g. for GraphSAGE, from the demo notebook:
```
generator = GraphSAGENodeGenerator(G, batch_size, num_samples)
train_gen = generator.flow(train_data.index, train_targets, shuffle=True)
graphsage_model = GraphSAGE(
    layer_sizes=[32, 32],
    generator=train_gen,
    bias=True,
    dropout=0.5,
)
```

**Expected behavior**
I think the generator argument should take the same object (i.e. generator before or sequence after the `.flow` method).

### Done Checklist
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Version number reflects new status
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] Documentation in repo
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by youph** [comment]
@adocherty the only class that requires a `Sequence` object created by `generator.flow()` method to construct the model is `HinSAGE` - it needs to know head node types that are inferred in `generator.flow()`. All other models (`GraphSAGE`, `GAT`, `GCN`) only require generators. 

It seems more logical to pass a generator rather than an iterator over training data (Sequence) to model constructor, but I don't know how to do this for HinSAGE...
