### ISSUE TITLE
Interpretability of saliency maps: scale node importance scores and edge importance scores  to be on the same scale 

### ISSUE THREAD

**Issue by annitrolla** [stellargraph/stellargraph#500]
### Description
Current implementation of gcn saliency maps outputs node importance scores and edge importance scores on different scales, that makes it difficult to compare. It would be very useful from a practical point of view to find a way to have values on a same scale. 
### User Story
As a: data scientist
I want: to compare importance scores of edge and node importance
so that: I will be able to answer a question: "what contributes to the prediction more: features of a node or a structure (e.g information from the neighborhood)"

### Done Checklist (Development)
- [ ] Assumptions of the user story met
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request build on CI
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Branch and Pull Request pass integration tests on CI
- [ ] Version number reflects new status
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] Documentation on Google Docs
- [ ] Documentation in repo
- [ ] CHANGELOG.md updated

**Comment by dubbsbrandon** [comment]
I'd also really like to have this implemented if possible.

**Comment by kjun9** [comment]
So I think this is currently a problem because of the way we've defined "node importance"

```
The importance of the node is defined as the sum of all the feature importance of the node.
```

We need to allow for different ways to aggregate the set of feature importances of a node to produce a "node importance" so that the resulting value becomes comparable to the link importance value. 

It's not clear to me exactly which aggregation method would be "correct" - I think `mean` or `max` could make sense? If you have time, I'm curious if you have any other thoughts on this @annitrolla @youph since you're both probably more familiar with this than I am!

**Comment by kjun9** [comment]
Or maybe taking the magnitude of the feature importances vector makes sense too?

**Comment by kjun9** [comment]
Okay I've thought a bit more about this:

We've defined node importance as the sum of the individual feature importances of a node. Feature importance is the partial derivative of the prediction output w.r.t. a particular feature value. So then node importance is basically how the output moves if you nudge all of the features at once. 

For instance, if you have `feature_importances=[2, 1, -1, 1]`, if you nudge the first feature by `0.1` you'd expect the output to move up by roughly `0.1 * 2 = 0.2`. If you nudge all features by `0.1` you'd expect the output to move by roughly `0.1 * sum([2, 1, -1, 1]) = 0.3`. This is our definition of node importance currently:
```
node_importance = sum(feature_importances)
```

Maybe you could argue it's a fairer comparison if you scale the "nudge" itself so that the total magnitude of the nudge remains constant. The partial derivative values represent movement w.r.t. a nudge of 1. So to nudge 4 features at once, we want to scale the nudges so that `sqrt([nudge**2 for nudge in nudges]) == 1` so then each nudge should be `sqrt(1/4)`. So with this definition then node importance becomes:
```
node_importance = sum(feature_importances) / sqrt(len(feature_importances))
```

Sorry for the lack of correct mathematical terms in places, but that's as far as my general intuition got me, hopefully makes sense? @annitrolla

**Comment by youph** [comment]
@kjun9 while it is correct that "raw" feature importances are gradients of the prediction with respect to features, what we output are the "integrated" feature importances, which are the path integrals of those gradients along the paths of feature change from current value to 0 - i.e., they tell how much the prediction would change if the corresponding feature is set to 0.

**Comment by kjun9** [comment]
@youph Yes, sorry forgot to mention that - I think the same thing applies, we still want to normalise the output so that it's as though we've only moved the whole set of features by a unit vector. 

> "integrated" feature importances, which are the path integrals of those gradients along the paths of feature change from current value to 0

From what I could understand from the implementation, I thought it was actually adding up the integral from 0 to 1? Or is that the same thing somehow? In `stellargraph/utils/saliency/integrated_gradients.py`:
```python
        total_gradients = np.zeros(X_val.shape)
        for alpha in np.linspace(0, 1, steps):
            X_step = X_baseline + alpha * X_diff
            total_gradients += self.get_node_masks(
                node_idx, class_of_interest, X_step, A_index, A_val
            )
        return np.squeeze(total_gradients * X_diff, 0)
```

So I think we still integrate from 0 to 1, but just scale the values so that the **total** movement across the whole feature vector is a unit vector (this is a more concise description to save myself from all the nudging analogy above, thanks to @huonw )

**Comment by kjun9** [comment]
@youph sorry I read the code a bit wrong, you're right it's the integral from 0 to the current feature value! ... which now makes me think this doesn't need any scaling at all 🤔

**Comment by youph** [comment]
> @youph sorry I read the code a bit wrong, you're right it's the integral from 0 to the current feature value! ... which now makes me think this doesn't need any scaling at all for the integrated gradient approach 🤔

I think the issue is about relative scaling of node vs edge importances, to make sure they are comparable. Considering node importances in isolation (that is, without comparing them to edge importances) does not require scaling - same goes for edge importances in isolation. But it would be useful to compare node and edge importances against each other.

Note that the different importance scores, calculated via integrated gradients, answer different questions:
- for node feature: how much the model's prediction score for the chosen class of interest would change if that feature is set to 0 from its current value
- for node: the sum of the node's feature importances as defined above. This is _approximately_ how much the model's prediction score for the chosen class of interest would change if all node features are reset to 0s (the key word is "approximately"! - let me know if it's unclear why this is so)
- for edge: how much the model's prediction score for the chosen class of interest would change if this edge were removed or added.

**Comment by kjun9** [comment]
@youph 

> I think the issue is about relative scaling of node vs edge importances, to make sure they are comparable. Considering node importances in isolation (that is, without comparing them to edge importances) does not require scaling - same goes for edge importances in isolation. But it would be useful to compare node and edge importances against each other.

I'm confused about they are not already comparable? If I want to know how a prediction changes when turning off an edge vs turning off a set of node features, aren't the current set of importance values showing exactly that comparison?

**Comment by youph** [comment]
Correction: the importance score for nodes should be
```
for nodes: the sum of the node's feature importances as defined above. This is equal to how much the model's prediction score for the chosen class of interest would change if all node features are reset to 0s
```
The reason is that the line integral of the model score gradient along a path from 0 to $\mathbf{r}$, where $\mathbf{r}$ is the node's feature vector, is path-independent.

**Comment by youph** [comment]
> If I want to know how a prediction changes when turning off an edge vs turning off a set of node features, aren't the current set of importance values showing exactly that comparison?

Not sure. I think it would become clear in synthetic experiments like these: https://docs.google.com/document/d/1RGdUEv9eIn7sZonADgjKx1Hx9EfzygwP5tIw8s-39cI

**Comment by youph** [comment]
The difficulty answering the question of whether those are comparable lies in the difference of the `Do` operations behind the node and edge importances: setting all node features to 0s vs removing an edge. These "interventions" are not equivalent in general, and I'm not even sure they are equivalent for the edge nodes (nodes on the edge of a graph)... This incompatibility could render comparison of node and edge importances meaningless.

**Comment by annitrolla** [comment]
I agree with @youph that the notion of comparing the effect of an edge deletion on prediction scores vs. sum of feature importances being zero is not really clear. I'm closing this issue for now, but let you know if I have any ideas how to improve it.
