### ISSUE TITLE
questions about input layer (model summary) 

### ISSUE THREAD

**Issue by mimisen-boop** [stellargraph/stellargraph#509]
Hi, I'm new to graph cnn and doing some [stellargraph tutorial](https://stellargraph.readthedocs.io/en/stable/quickstart.html). And I ran the GraphSAGE Cora Node Classification Example, `graphsage-cora-example.py`.  
This is the part of the model summary.

````
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_2 (InputLayer)            [(None, 20, 1433)]   0                                            
__________________________________________________________________________________________________
input_3 (InputLayer)            [(None, 200, 1433)]  0                                            
__________________________________________________________________________________________________
input_1 (InputLayer)            [(None, 1, 1433)]    0                                            
__________________________________________________________________________________________________
````
I have two questions.
1. Why are there multiple input layers?
2. What are these numbers of output shape indicates?  I know the number 1433 is come from unique words of cora dataset.(right?)

I read the original paper of [GraphSAGE](https://cs.stanford.edu/people/jure/pubs/graphsage-nips17.pdf), but still I don't understand...

**Comment by adocherty** [comment]
Hi,

Thanks for trying out StellarGraph!

The multiple inputs here represent the neighbourhood features that are sampled by GraphSAGE, each input represents the sampling for k hops from the starting or head node. A k-layer GraphSAGE model requires inputs from k hops away and will have (k+1) inputs (including the zeroth hop).

Here there are three inputs for a two-layer model. They represent the head node features (of size `(1,n_feature)` as there are only one head node for a node classification model). The next input contains a sample of 20 neighbours of the head node and is of size `(20, n_feature)`. The third input contains a sample of 20 neighbours of the 20 neighbours sampled in the previous input, therefore 200 total samples and the input is of size `(200,n_feature)`. In this example the number of features for each node is `n_feature=1433`. 

This is due to the fact that the sampling of the nodes is done external to the model, so that graphs larger than can be fit into memory can be used.  Additionally, these inputs are not expected to be supplied by the user. The generator functions such as `GraphSAGENodeGenerator` are responsible for creating the sampled feature inputs for the model.

I hope this helps!

Regards,
Andrew

**Comment by mimisen-boop** [comment]
Thank you! It helped me a lot. But why are there two layers in this model? Can it be changed to three or more layers?

**Comment by youph** [comment]
"The third input contains a sample of 20 neighbours of the 20 neighbours sampled in the previous input" - should be a sample of 10 neighbours of the 20 neighbours...

**Comment by mimisen-boop** [comment]
yeah I thought so! the number '200' means 20*10 of neighbours, right?

**Comment by youph** [comment]
@mimisen-boop yes, there can be an arbitrary number of layers in the model. However, adding more layers means increasing the "expressive power" of the resulting model (as each layer comes with its own learnable weights), and might lead to overfitting and worse generalisation power - e.g., see Figure 5 in the [GCN paper](https://arxiv.org/pdf/1609.02907.pdf).

**Comment by mimisen-boop** [comment]
Thank you so much. Now I get it!

**Comment by youph** [comment]
@mimisen-boop to change the number of layers in that example, you'd need to change the `--neighbour_samples` and `--layer_size` arguments. E.g., to have a 3-layer model, one can set them to something like `--layer_size 20 20 20` and `--neighbour_samples 20 10 5` , or whatever (these values are hyperparameters too).

**Comment by PauloJhonny** [comment]
@youph Hi. I’m using graphsage for link prediction and it’s really amazing. Now, I’m trying to tune the hyperparameters, but without success. Do you have an example of how I could use random search, for example, in order to tune the hyperparameters?

Thank you.

**Comment by youph** [comment]
@PauloJhonny thanks for trying the library! We don't have an example with hyperparameter tuning, but I'd suggest using the `hyperopt` python library: https://github.com/hyperopt/hyperopt
