### ISSUE TITLE
Stellargraph on time-varying graphs

### ISSUE THREAD

**Issue by mimisen-boop** [stellargraph/stellargraph#517]
I'm interested in applying this to time-varying graph data,. Is it possible? I want this model to learn time-varying graph data and challenge the node classification task.

**Comment by adocherty** [comment]
Thanks for the comment. We are looking at potential ways to use time-varying information and hope to incorporate this functionality into the library in the future.

Do you have any algorithms or use-cases in mind?

Regards,
Andrew

**Comment by huonw** [comment]
StellarGraph now incorporates several algorithms for graphs that have time information:

- graphs with times associated with edges: https://stellargraph.readthedocs.io/en/stable/demos/link-prediction/ctdne-link-prediction.html
- graphs with time series as features in each node: https://stellargraph.readthedocs.io/en/stable/demos/time-series/index.html

It's been several months since any update on this issue, so with the above and without more specifics, I'm going to call this resolved. Please let us know if you have any issues for further thoughts. If not, we'll close this in a week or so (but we can always reopen after too).
