### ISSUE TITLE
MemoryError when creating StellarGraph object with large node_features

### ISSUE THREAD

**Issue by lamurian** [stellargraph/stellargraph#537]
**Describe the bug**
I got a `MemoryError` when assigning large data frame as `node_features` using `StellarGraph` function from `stellargraph.core`.

**To Reproduce**
```
import networkx as nx
import scipy.io as sio
from stellargraph.core import StellarGraph

# Data parsing with scipy.io as sio and pandas as pd
data = sio.mmread('_data/sparse.mtx')
feature = sio.mmread('_data/sparse-feature.mtx')
feature = pd.DataFrame.sparse.from_spmatrix(feature)

# Create graph object using networkx as nx
g = nx.from_scipy_sparse_matrix(data)

# Create StellarGraph object
gs = StellarGraph(g, node_features=feature) # MemoryError
```

Resulting error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lam/.local/lib/python3.6/site-packages/stellargraph/core/graph.py", line 786, in __init__
    super().__init__(incoming_graph_data, **attr)
  File "/home/lam/.local/lib/python3.6/site-packages/stellargraph/core/graph.py", line 381, in __init__
    node_features, type_for_node, node_types, dtype
  File "/home/lam/.local/lib/python3.6/site-packages/stellargraph/core/graph.py", line 216, in _convert_from_node_data
    {node_type: data}, node_type_map, node_types, dtype
  File "/home/lam/.local/lib/python3.6/site-packages/stellargraph/core/graph.py", line 182, in _convert_from_node_data
    data_arr = arr.values.astype(dtype)
  File "/home/lam/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5443, in values
    return self._data.as_array(transpose=self._AXIS_REVERSED)
  File "/home/lam/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 822, in as_array
    arr = mgr._interleave()
  File "/home/lam/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 840, in _interleave
    result = np.empty(self.shape, dtype=dtype)
MemoryError
```

**Expected behavior**
`StellarGraph` object should be created as a result.

**Desktop (please complete the following information):**
 - OS: Linux 5.3.11_1 64-bit
 - RAM: 8 GB
 - Stellargraph version 0.8.2

**Data used**
Data is not publicly available, but I used a sparse block diagonal matrix (shape: 158,950 x 158,950) parsed as `networkx` graph and a dense block diagonal feature matrix (shape: 158,950 x 14,450) parsed as `pandas.DataFrame`.

**Additional context**
I'm sorry for not providing sparse.mtx and sparse-feature.mtx file due to confidentiality reason, but I hope previous description on data shape may help you to understand its construct.

While monitoring memory consumption, I observed that the RAM only used up to 55% of its total capacity, and the swap was not used at all. While running the code, I only used TTY + `tmux` with only `vim`, `top` and `python` session running. Moreover, I also made sure no other memory-hogging processes running in the background. So I'm certain the memory bottleneck is most likely caused by `python`.

**Comment by youph** [comment]
@lamurian could you estimate the memory sizes of the `feature` dataframe? This can be done by 
```sys.getsizeof(feature)/1024**3``` (in GB)
I think the memory error you are getting is not very surprising, as the estimated memory requirement for the pandas data frame of floats of shape (160,000, 15,000) is ~18GB. In your case it could be less, considering it is made from a sparse matrix, but it could still be quite large.

**Comment by huonw** [comment]
Hi @lamurian, as @youph said, the size of a dense feature matrix is potentially as large as 18GB, depending on the type of the features.

```python
>>> def dense_size(nodes, features, bytes_per_f): return (nodes * features * bytes_per_f) / 1000**3
... 
>>> dense_size(158950, 14450, 8) # float64
18.37462

>>> dense_size(158950, 14450, 4) # float32
9.18731
```

As the above suggests, you may be able to half the memory foot-print of the features by switching to a different datatype, if you're using `np.float64` features (`feature.dtype`). However, it sounds like you're actually using the `scipy.sparse.bsr_matrix` type, not a dense matrix, so this estimate is presumably much larger than the reality.

Instead of sharing the actual data, potentially you could share some suggestive statistics, that allow us to simulate similar data?

For features:

- `features != 0` will create a `bool` matrix which just has `True` where the features are nonzero, and thus not contain much information about the real data: `scipy.io.mmwrite("all-ones-features.mtx", features != 0)`
- if that's still too much, we can just look at the blocks themselves that contain non-zeros, by setting the data matrix to all ones; this will make the features coarser by ignoring zeros inside each block: `block_ones_features = scipy.sparse.bsr_matrix((np.ones_like(features.data), features.indptr, features.indices)); scipy.io.mmwrite("block-ones-features.mtx", block_ones_features)`
- finally, the simplest but least informative option would be high-level descriptive features like `features.getnnz()` and `features.data.shape` which will just tell us the number of elements that aren't missing from the sparse matrix and the size of each block.

For the graph structure, knowing the number of edges would be great (`data.getnnz()` or `g.number_of_edges()`), or even the (out) degree of each node `data.sum(axis=0)`.

---

Finally, in stellargraph 0.10.0 we released a new `StellarGraph` class that offers much lower memory use. The current method to construct it is to pass the nodes and edges as a Pandas dataframe, with the edges as an edge list: this might look something like

```python
coo = data.tocoo()

edgelist = pd.DataFrame({"source": coo.row, "target": coo.col, "weight": coo.data})
gs = StellarGraph(feature, edgelist)
```

If you're still using StellarGraph, we'd love to work with you to get this working for you.

**Comment by huonw** [comment]
It's been 2 months without any update, so I'm going to assume that the problem is resolved or otherwise not relevant. If we haven't heard otherwise in a week or so, we'll close. (But, even if we close, feel free to just let us know later, and we can reopen/continue the discussion.)
