### ISSUE TITLE
Generating embeddings for entire graphs

### ISSUE THREAD

**Issue by sbhttchryy** [stellargraph/stellargraph#693]
Is there a way to generate embeddings for subgraphs/full-graphs ?

**Comment by huonw** [comment]
Just so that we're crystal clear and talking about the same thing: do you have a sequence of several graphs (or subgraphs), and want to use each one as a train/test example to generate an embedding for a whole graph/subgraph? E.g. if `graphs` is a list of graphs:

- `graphs[0]` -> `[1, 0, 0]`
- `graphs[1]` -> `[1, -1, 1]`
- `graphs[2]` -> `[0, 0.5, 1]`

**Comment by PantelisElinas** [comment]
Hi @sbhttchryy 

thanks for using our library.

StellarGraph does not currently implement graph classification algorithms. However, I can suggest one approach for the following problem: Given that you have a single graph, G, and you want to calculate embeddings for subgraphs, G_i, that you can then train a classification model for, e.g., predict one of C classes for each G_i, you can do the following.

Use Node2Vec or DeepWalk to calculate embeddings for each of the nodes in the graph. Then for each G_i, calculate an embedding vector that is some function of the embeddings calculated for the nodes in G_i. For example, you can calculate the mean of the node embedding vectors. Then, you can use these vectors to train a model for graph classification. 

Note that the above would not work if you had a collection of disconnected graphs because the node embeddings across graphs would not be particularly meaningful. 

Hope this helps!

P.

**Comment by sbhttchryy** [comment]
Hi @PantelisElinas  thank you very much for your response. Indeed it is a work around, but do you think it will work for weighted/attributed edges?

**Comment by sbhttchryy** [comment]
Hi @huonw , thank you for your response. The problem is as follows: I have a big graph G, and I want to generate embeddings for the subgraphs in G, so that I can use the vector generated from the subgraph embeddings for downstream tasks. I hope this helps. I am looking forward to any solution you find.

**Comment by PantelisElinas** [comment]
Hi @sbhttchryy 

StellarGraph supports weighted random walks, i.e., weighted Node2Vec/DeepWalk. For an example see https://github.com/stellargraph/stellargraph/tree/develop/demos/node-classification/node2vec

Out Metapath2Vec implementation does not support edge weights. You can treat your heterogeneous graph as a homogeneous one to get the embeddings using weighted Node2Vec/DeepWalk. Unfortunately, this is an approximation that might not give you the best results.

Regards,

P.

**Comment by huonw** [comment]
Hi @sbhttchryy, we've now landed an experimental approach to (supervised) graph classification, which can be used to generate embeddings for graphs. There's a demo notebook at https://github.com/stellargraph/stellargraph/blob/develop/demos/graph-classification/supervised-graph-classification.ipynb ([permalink](https://github.com/stellargraph/stellargraph/blob/5c26f2da9bcba2c62bd4225e9177ff4c01e7f748/demos/graph-classification/supervised-graph-classification.ipynb), that won't get updates, but will always exist).

To get vector embeddings for each graphs after training the supervised model, you can create a model using the tensor output of one of the earlier non-prediction layers (such as `x_out` in that notebook), similar to how it is done for node classification (for example, the "Node embeddings" section at the end of https://github.com/stellargraph/stellargraph/blob/develop/demos/node-classification/gcn/gcn-cora-node-classification-example.ipynb ([permalink](https://github.com/stellargraph/stellargraph/blob/5c26f2da9bcba2c62bd4225e9177ff4c01e7f748/demos/node-classification/gcn/gcn-cora-node-classification-example.ipynb)).

**Comment by huonw** [comment]
In the [recent 1.1.0 release](https://github.com/stellargraph/stellargraph/releases/tag/v1.1.0), we've added support for distance/comparison based methods for training unsupervised graph embeddings algorithms: https://stellargraph.readthedocs.io/en/v1.1.0/demos/embeddings/gcn-unsupervised-graph-embeddings.html

Thus, I'm going to call this issue resolved. Please do let us know if you have any issues or further thoughts, if we don't hear, we'll close this in a week or so (but we can always reopen after too).
