### ISSUE TITLE
Is it possible to use Attri2vec to directly generate node embeddings ?

### ISSUE THREAD

**Issue by sbhttchryy** [stellargraph/stellargraph#873]
Hi, first of all, congratulations and thank you for making this library. I am curious, if it is possible to directly generate the node embeddings for using the attri2vec model without performing any classification task first?

**Comment by kjun9** [comment]
Hi @sbhttchryy 

This demo notebook demonstrates how you can generate node embeddings using unsupervised attri2vec: https://github.com/stellargraph/stellargraph/blob/master/demos/embeddings/stellargraph-attri2vec-citeseer.ipynb

Unsupervised learning in this context is always phrased as a sort of *link prediction* task in StellarGraph, where the links you predict are *context pairs* obtained from running random walks on the graph. 

The random walks are taken care of internally, but the Keras model is exposed and still uses a link classification layer, so that might've been slightly deceiving at first if you've come across this notebook already!

Let us know if you have problems following/running the notebook

**Comment by huonw** [comment]
Hi @sbhttchryy, did @kjun9's answer above allow you to get something working? If not, is there something else that is causing problems or something else that you need some assistance with?

**Comment by sbhttchryy** [comment]
> Hi @sbhttchryy, did @kjun9's answer above allow you to get something working? If not, is there something else that is causing problems or something else that you need some assistance with?

**Comment by sbhttchryy** [comment]
Yes, thank you very much @kjun9  and @huonw
