### ISSUE TITLE
Demo directory for link prediction via random walks contains a very large amount of code

### ISSUE THREAD

**Issue by kjun9** [stellargraph/stellargraph#896]
### Description

[`demos/link-prediction/random-walks`](https://github.com/stellargraph/stellargraph/tree/4070ccf24d67802a08a9f70ca3e7567a0a53a7fc/demos/link-prediction/random-walks/utils) contains a `utils` module which contains a substantial amount of code. 

We should move as much of this into the core library as possible, since moving this into the library means:
* the code is much easier to maintain, and can be tested independently from the demos
* it's easier to reuse it across more notebooks
* a user can follow/copy the demo notebook without having to dig into / copy a whole mini module shipped alongside the demo

### User Story

**As** a data scientist

**I want to** use stellargraph functions to help me do link prediction instead of more code shipped with a demo

**So that** my job is easier

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by huonw** [comment]
Not only does this contain a large amount of code, but it seems to contain its own implementation of node2vec https://github.com/stellargraph/stellargraph/tree/develop/demos/link-prediction/random-walks/utils/node2vec (taken seemingly directly from https://github.com/aditya-grover/node2vec) rather than using the one in the library.
