### ISSUE TITLE
Allow UnsupervisedSampler to take "walker" as a parameter

### ISSUE THREAD

**Issue by ericbroda** [stellargraph/stellargraph#919]
### Description

UnsupervisedSampler is limited to using "UniformRandomWalk" as the node walker/sampler.  It would be ideal to allow the walker to be selected/provided by the developer.

### User Story

As a developer I would like flexibility in choosing which walker I can use, and also be able to write my own walkers and have them used by UnsupervisedSampler

So that I can techniques to improve model performance

### Suggested Solution:

1. Update signature of UnsupervisedSampler __init__ method to include an optional "walker" parameter:
~~~~
def __init__(self, G, nodes=None, length=2, number_of_walks=1, seed=None, walker=None):
~~~~

2.  Modify code (line 59) in __init__  to use the provided walker as follows:
~~~~
# self.walker = UniformRandomWalk(G, seed=seed)
if walker:
    self.walker = walker
else:
    self.walker = UniformRandomWalk(G, seed=seed)
~~~~

Developers that wish to use this functionality would now call UnsupervisedSampler as follows:
~~~~
: 
: 
from stellargraph.data.explorer import BiasedRandomWalk
walker = BiasedRandomWalk(Gs, seed=42)
unsupervisedSamples = UnsupervisedSampler(Gs, nodes=labels, length=walk_length, number_of_walks=num_walks, seed=42, walker=walker)
: 
: 
~~~~

**Comment by kjun9** [comment]
Thanks for your suggestion @ericbroda ! I agree with you that it makes sense to allow the walker being used to run the unsupervised sampler be flexible/implemented by a user.

I can think of a few more pieces of work on top of your suggested solution that would make this feature more useable long term:
- a custom walker from the user should probably be implementing one or two methods in an existing parent class in the library, to guide the user how a "walker" should behave. Currently this parent class would be `GraphWalk` but it's being used too broadly at the moment and is not really designed as an interface that can readily be implemented by users. I'm thinking it might make sense split it into two different classes `GraphWalk` and `GraphSampler` and go from there (happy to explain this more if you're interested)
- currently a lot of parameters are passed into the `run` method of a walker class (e.g. `BiasedRandomWalk` takes parameters like `p` and `q` in `run` instead of the constructor), but `UnsupervisedSampler` will be calling `walker.run` internally, so as it stands, these parameters won't be configurable. This probably needs some sort of refactoring to allow the user to pass in a walker class to `UnsupervisedSampler` that has custom `run` parameter values, or just move these parameters to the constructor if that makes more sense.

The current set of algorithms in the library haven't required this flexibility, but let us know if you have any particular use-cases in mind when you're wanting to use `UnsupervisedSampler` with different types of walkers, as this could help us prioritise this issue and maybe push out something sooner.

**Comment by ericbroda** [comment]
@kjun9 I agree with your comments.  A suitable base class (GraphSampler) would be ideal.  As you mention, a flexible but consistent manner of specifying walker parameters would also be ideal.
I made changes on my own to allow use of the BiasedRandomWalk to test use-cases and it addresses my immediate needs.

The use-case I am trying to support is implemented using StellarGraph's GraphSAGE implementation.  However, much of the knowledge in my application is captured in relationships (weights) between nodes.  The current sampler uses Uniform walkers which does not consider weights, but the Biased walker appears to use weights appropriately.

That being said, I can see where I would use more than just edge weights and also use other edge attributes during sampling.  I fully expect to write a custom walker that addresses my specific needs but I need the the implementation to be extended to allow my own implementation.

**Comment by kjun9** [comment]
Hi @ericbroda 

This should be available in the next release of the library! There is now a new `walker` parameter when creating an `UnsupervisedSampler`, and a new base class `RandomWalk` which can be extended with custom implementations.

#1187 :

> This introduces a new base class RandomWalk which is a more specific type 
compared to the existing GraphWalk class. A RandomWalk class is defined as 
having a run method which takes a list of node IDs and returns a list of 
random walks (list of list of node IDs). Currently these classes belong to 
this type:
>
> * UniformRandomWalk
> * BiasedRandomWalk
> * UniformRandomMetaPathWalk
>
> It's useful to define this type, since these are all suitable for use with 
UnsupervisedSampler, and so we introduce a new walker parameter to 
UnsupervisedSampler to allow for some flexibility instead of being 
hardcoded to use UniformRandomWalk.
