### ISSUE TITLE
Create a demo notebook to replace script for random walk link prediction

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#934]
### Description

The demo script for random walk link prediction was restored for #895 as it does significantly more than the Jupyter demo notebook.   As part of our plan to replace scripts with notebooks, we should remove `demos/link-prediction/random-walks/main.py` and replace it with a suitable demo (eg heterogenous with `BlogCatalog3` dataset?)

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo

**Comment by kjun9** [comment]
Hmm actually this is currently a bit difficult to do due to https://github.com/stellargraph/stellargraph/issues/907 - that site's been down for a while now, probably need to just rewrite the demo with a different dataset?

**Comment by timpitman** [comment]
I think we should probably just upload that dataset to figshare?

**Comment by kjun9** [comment]
Seems like my laptop can't handle the current metapath2vec demo with blog catalog - I've reduced some of the random walk parameters to:
```
num_walks = 1  # previously 10
walk_length = 20  # previously 80
```
but the graph is large enough that the random walks have been running for a few hours without any visible progress, will try reduce the parameters further..

**Comment by kjun9** [comment]
I think it might be too much of a rush to try get this in with https://github.com/stellargraph/stellargraph/pull/1399 and https://github.com/stellargraph/stellargraph/pull/1392 so I'm thinking we could just remove the `utils` directory for 1.0: https://github.com/stellargraph/stellargraph/pull/1462

Seems unlikely that the script is being run or is able to be run, and it would clean up our demos for the release. Unsupervised Metapath2Vec is being demo'd via `demos/embeddings/stellargraph-metapath2vec.ipynb` which does hint at the bottom of the notebook:
```
## Downstream Tasks

The node embeddings calculated using Metapath2Vec can be used as feature vectors in a downstream task such as node attribute inference (e.g., inferring the gender or age attribute of 'user' nodes), community detection (e.g., clustering of 'user' nodes based on the similarity of their embedding vectors), and link prediction (e.g., prediction of friendship relation between 'user' nodes).
```
So that's probably more helpful than the existing scripts
